# -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=2080 -Djava.net.socks.version=5
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.208
loader_version_range=[1,)

## Mod Properties
mod_id=tfcwoodwork
mod_name=TFC Woodworking
mod_license=MIT
mod_version=1.21.1-1.2.0
mod_group=su.uTa4u
mod_group_id=su.uTa4u.tfcwoodwork
mod_authors=uTa4u
mod_description=Simple addon for TFC.\nMakes crafting wooden things more immersive.

#mixin_version=0.8.5
tfc_version=7035035
patchouli_version=1.21.1-92-NEOFORGE
jei_version=19.22.1.316
jade_version=15.10.3+neoforge
#firmaciv_version=5737719
#alekiships_version=5963449