modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/uTa4u/TFC-Woodworking/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://github.com/uTa4u/TFC-Woodworking" #optional
logoFile="tfcwoodworking.png" #optional A file name (in the root of the mod JAR) containing a logo for display
authors="${mod_authors}" #optional
description='''${mod_description}''' #mandatory

[[dependencies.tfcwoodwork]]
    modId="tfc"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tfcwoodwork]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tfcwoodwork]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"